### ISSUE TITLE
SqlDatabasePermission: Cannot grant or remove connect permission to the guest user

### ISSUE THREAD

**Issue by imarambiocatan** [dsccommunity/SqlServerDsc#1134]
I'm probably doing something that i should not. I am dynamically generating a number of mof files based on my current environment to test a few controls with DSCEA but in any case the mof file that gets generated for my server has a section that looks like the following

```
instance of MSFT_SqlDatabasePermission as $MSFT_SqlDatabasePermission1ref
{
ResourceID = "[SqlDatabasePermission]RevokeGrant_guest_model";
 Permissions = {
    "Connect"
};
 ServerName = "<edited>";
 InstanceName = "MSSQLSERVER";
 Ensure = "Absent";
 SourceInfo = "<edited>";
 Name = "guest";
 ModuleName = "SqlServerDsc";
 PermissionState = "Grant";
 ModuleVersion = "11.2.0.0";
 Database = "model";

 ConfigurationName = "SQL_config";
};
```
using dscea against my server results in something like

WARNING: PowerShell DSC resource MSFT_SqlDatabasePermission  failed to execute Test-TargetResource functionality with error message: Login 'guest' does not exist on SQ
L server 'abbsus201\MSSQLSERVER'.

But it clearly does
PS > ($(Get-SqlInstance -ServerInstance localhost).Databases | where-object { $_.name -notin @("master",
"msdb", "tempdb") -and "guest" -in $_.users.name }).name
model
ReportServer
ReportServerTempDB
SUSDB

**Comment by johlju** [comment]
We should be able to grant or revoke connect permission as per [Best Practices Recommendations](https://docs.microsoft.com/en-us/sql/relational-databases/policy-based-management/guest-permissions-on-user-databases?view=sql-server-2017#best-practices-recommendations). But because this resource wrongly handles logins (which I think only SqlServerLogin should do), that was raised in issue #848 too. this resource can handle the guest user because their will never be an accompanying login for that user.

**Comment by johlju** [comment]
I will label this as a bug and help wanted so that someone in the community can run with this.

**Comment by johlju** [comment]
Oops, wrongly closed the issue. Sorry about that. Reopened.

**Comment by johlju** [comment]
This will be fixed in the next release.
