### ISSUE TITLE
SqlServerDsc: Consider keeping the removed resources 

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#1543]
Consider keeping the removed resources as deprecated but without any examples, unit tests, and integration tests to minimize the resources to break builds.
They must also be excluded from code coverage when the unit tests does not exist to not negatively effect the coverage. If possible they should also be removed from HQRM tests and code coverage so they doesn't break builds if HQRM tests gets improved.

**Comment by johlju** [comment]
Also consider adding a comment in each code file that the resource is deprecated, and output a verbose message telling that the resource is deprecated (from each *TargetResource function).

**Comment by ykuijs** [comment]
In SharePointDsc we only remove things in major versions. With the release of v2.0, we deprecated two resources by making them do exactly the thing you are describing. In v3.0, we removed them altogether. So your idea totally makes sense ;-)

**Comment by johlju** [comment]
Thanks @ykuijs I did that with one resource now, I will do the same for the others that I initially wanted to just delete (because they were replace by other resources). Then we will see how long we wait until we remove them (in a breaking release).

Do you consider a deprecated resource a breaking change? Or do you deprecate a resource in a minor release but once the deprecated resource is removed you make a breaking release?

**Comment by ykuijs** [comment]
In our case, we considered the deprecation a breaking change since this meant that existing configs wouldn't function anymore. They wouldn't break with error messages or exceptions, but still they wouldn't deploy SharePoint anymore. And because of dependencies, other resource could break as a result. So in v2 we added the breaking change with the deprecation and in v3 the breaking change with removing the resource altogether.

**Comment by johlju** [comment]
This has now been done for each of the four deprecated resources.
