### ISSUE TITLE
SqlWaitForAG: Does not evaluate if the Availability Group was successfully created

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#1569]
SqlWaitForAG resource evaluates if the Windows Failover Cluster role/group has been created. But the Windows Failover Cluster role/group is created before the Availability Group is in a ready state. When the Windows Failover Cluster role/group is found the resource will wait one more time according to the value of `RetryIntervalSec` before returning. There is currently no check to validate that the Availability Group was successfully created and is in a ready state.

**Comment by Fiander** [comment]
hmm, wanting to pick this one up.
but I think this will be a breaking change. Eg I will need to introduce two extra parameters: $ServerName and $InstanceName.
will that be a problem?

**Comment by Fiander** [comment]
[](https://github.com/Fiander/SqlServerDsc/tree/WaitForAg)
the fix is done, only i've mesed up with the SqlRole. SqlRole has messed up my masterBase, and waitforAg now depends on this messed up base.

**Comment by AndreasMWalter** [comment]
@Fiander @johlju 
This is indeed a breaking change and also provides the following problem:
I use this resource to wait for the AG (that was created on the primary node), before adding the replica on the secondary. (I assume this is the intended purpose?)
However rather than looking on the primary for the AG it will look for the AG on the secondary which does not yet have it, since SqlAGReplica depends on this resource.
![image](https://user-images.githubusercontent.com/38529659/116212211-e36b3200-a744-11eb-9513-9c223ce6a1f5.png)
So unless I have missunderstood the resource this basically breaks every configuration.

**Comment by AndreasMWalter** [comment]
> @Fiander @johlju
> This is indeed a breaking change and also provides the following problem:
> I use this resource to wait for the AG (that was created on the primary node), before adding the replica on the secondary. (I assume this is the intended purpose?)
> However rather than looking on the primary for the AG it will look for the AG on the secondary which does not yet have it, since SqlAGReplica depends on this resource.
> ![image](https://user-images.githubusercontent.com/38529659/116212211-e36b3200-a744-11eb-9513-9c223ce6a1f5.png)
> So unless I have missunderstood the resource this basically breaks every configuration.

So just that you know, I have fixed this with using WaitForAll Resource instead of SqlWaitForAG, still would be nice to know the intended purpose of this DSC Resource, since waits on the same node can be done with dependencies anyway.

**Comment by powertim** [comment]
Hi @AndreasMWalter , could you please show me some example configuration with WaitForAll instead of SqlWaitForAG ?
As I'm using Ansible to apply DSC config, I'm afraid I can't use this method.
Thanks for your help.
