### ISSUE TITLE
Wiki Incomplete

### ISSUE THREAD

**Issue by jeremiahmoree-adot** [dsccommunity/SqlServerDsc#1734]
As a new user to this module I am still trying to understand how it works and how to use it.   The primary docs seem to be the wiki.

The first thing I notice is a lack of a single full stack example.  All of the examples in the wiki are for creating configurations to feed to another process.  I cannot find any instructions in this  WIKI for how to USE those configurations.  From other places on the web it looks like installing the sql server requires 3 steps.  First, create the configurations.  Next, process the configuration into a specific format.  Lastl, run DSC.  Something like

`? Type configuration into the shell?  Put it in a file? Do something with it?`
`InstallSqlServer -Output $SECRETS -ConfigurationData $config`
`Start-DscConfiguration -Path $SECRETS -Wait -Verbose -Force `

Where is this documentation?  If it exists, please link to it in the GETTING STARTED sections of the WIKI HOME.   If it does not exist, please add something to the getting started section or create a dedicated page for it.

In my case I'm attempting to install SSRS.  Does SSRS, SSAS, SSIS follow the same 3 steps?

**Comment by johlju** [comment]
There are different ways of applying a compiled configuration to a node. You can use Local Configuration Manager (LCM) that comes built-in to Windows, you can run a resource directly using `Invoke-DscResource`, or you can use Chef, Puppet, Azure, AWS, and other ways. Since there is not one way of applying a configuration to a node, the documentation for this module does now explain that nor will it (since the community can't keep it updated in this module). There are a lot of other sources that explain how to get started with DSC. 🙂 

Here one way is explained: https://docs.microsoft.com/en-us/powershell/dsc/managing-nodes/apply-get-test?view=dsc-1.1

DscWorkshop is a project that might be what you are looking for in regards of a full stack example https://github.com/dsccommunity/DscWorkshop, and in this community call there is a quick demo of it https://dsccommunity.org/community_calls/2021-11-17-notes.

> In my case I'm attempting to install SSRS. Does SSRS, SSAS, SSIS follow the same 3 steps?

If one node should have all three, then yes - you create a configuration for that node, compile the configuration, and apply the configuration (then optionally monitor for drift). If there are 3 nodes that should have SSRS, SSAS, SSIS respectively then you creat a configuration for each node that the feature property specifies what component should be installed. See wiki documentation for the resource SqlSetup.

**Comment by jeremiahmoree-adot** [comment]
Thank you for the information.  

It would be helpful to link to the Microsoft PS DSC documentation (or at least mention it) in the documentation/wiki for this project.  Many of us will be introduced to PS DSC through this project.  The local docs assume familiarity with the underlying technology which raises the bar for adoption and increases requests for support.  Though I went over the local docs many times I did not know that 'DSC' was a separate project.  It's not listed as a dependency (since it is provided by .Net Frameworks already mentioned?).   DSC and Desired State are somewhat generic terms.

Perhaps a prerequisite should be added to https://github.com/dsccommunity/SqlServerDsc/wiki?  
* Familiarity with Powershell Desired State Configuration (link here?)

**Comment by johlju** [comment]
We could do that, but since the docs are updated and can change URL we might use the generic search term: https://docs.microsoft.com/en-us/search/?terms=Desired%20State%20Configuration&scope=PowerShell

But I would have rather haved linked to the DSC Community site https://dsccommunity.org/configmgt/ that is meant to show-case different options, not just what Microsoft provides. Though it need contributors to update that. 

So for the time-being I'm happy to get a PR with the suggestion you suggested.

**Comment by jeremiahmoree-adot** [comment]
https://github.com/dsccommunity/SqlServerDsc/pull/1740

added some copy to prereqs on wiki.  see PR.
