### ISSUE TITLE
SQLRole: add domain account fails

### ISSUE THREAD

**Issue by jeremiahmoree-adot** [dsccommunity/SqlServerDsc#1739]
### Problem description

Attempting to add domain group to sysadmin role and it fails saying that the group is not in the local users.  That's because it's a domain group--not a local group.  This can easily be done with tsql--which is my workaround for now.  AFAIK I have followed the docs.

### Verbose logs

```text
VERBOSE: [JMOREESQLD00137]:                            [[SqlRole]Grant_sysadmin_for_dbas] Setting properties of the SQL Server role 'sysadmin'.
VERBOSE: [JMOREESQLD00137]: LCM:  [ End    Set      ]  [[SqlRole]Grant_sysadmin_for_dbas]  in 0.2350 seconds.
PowerShell DSC resource DSC_SqlRole  failed to execute Set-TargetResource functionality with error message: System.InvalidOperationException: Failed to add member 'DOMAIN\dba_admins' to the server role named 'sysadmin' on 'JMOREESQLD00137\MSSQLSERVER'. --->
System.Exception: System.Exception: Security principal 'DOMAIN\dba_admins' does not exist on SQL server 'JMOREESQLD00137'.
   --- End of inner exception stack trace ---
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
```

### DSC configuration

```powershell
This is excerpts of the relevant sections but I'll post more if someone really wants to see it

            SqlRole 'Grant_sysadmin_for_dbas' {
                ServerRoleName       = 'sysadmin'
                MembersToInclude     = 'DOMAIN\dba_admins'
                InstanceName    = 'MSSQLSERVER'
            }
```

### Suggested solution

no

### SQL Server edition and version

```text
SQL 2019 Standard development edition
```

### SQL Server PowerShell modules

```text
Name      Version    Path
----      -------    ----
SQLServer 21.1.18256 C:\Program Files\WindowsPowerShell\Modules\SQLServer\SQLServer.psd1
```

### Operating system

```text
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

### PowerShell version

```text
Name                           Value
----                           -----
PSVersion                      5.1.17763.2268
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.2268
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### SqlServerDsc version

```text
Name         Version Path
----         ------- ----
SqlServerDsc 15.2.0  C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\SqlServerDsc.psd1
```

**Comment by jeremiahmoree-adot** [comment]
Ah.  I see the problem.   The domain account is not added as a login to the server as part of SQLRole.   Isn't that implicit in the purpose of the SQLRole?  If it is to ensure that a particular user/group is added to a role and that relationship can't exist unless the user/group exists on the server shouldn't the code set that up for me?   Do I understand correctly that the goal of this module is to reduce the amount of manual work and other code I have to create?  Would there ever be a case where we would not want this module to do more mundane required work for me?

**Comment by johlju** [comment]
The problem is that if SqlRole would add the login prior to adding the principal to the role, then next instance in the configuration could be SqlLogin that removes the principal which would make a "ping-pong" behavior. So to make sure the desired state is correct the configuration should first set the desired SqlLogin then add the desired login to the correct group(s) using SqlRole. This way the same configuration could never remove an principal that is actually needed for the desired state.

**Comment by johlju** [comment]
The tool you are talking about is not this module or the resources, the "tool" is the configuration that will set the node to the desired configuration. The configuration can contain resources from many different modules. Ever instance of a resource can only contain a unique set of key properties.

When the following configuration is compiled it will make sure that no duplicate resource instances exist. The compiled configuration will add a new login, and then add that login to the role `MySqlRole`. 

```powershell
Configuration Example
{
    param
    (
        [Parameter(Mandatory = $true)]
        [System.Management.Automation.PSCredential]
        $SqlAdministratorCredential
    )

    Import-DscResource -ModuleName 'SqlServerDsc'

    node localhost
    {
        SqlLogin 'Add_WindowsUser'
        {
            Ensure               = 'Present'
            Name                 = 'CONTOSO\WindowsUser'
            LoginType            = 'WindowsUser'
            ServerName           = 'sqltest.company.local'
            InstanceName         = 'DSC'

            PsDscRunAsCredential = $SqlAdministratorCredential
        }

        SqlRole 'Add_ServerRole_AdminSqlforBI'
        {
            Ensure               = 'Present'
            ServerRoleName       = 'MySqlRole'
            Members              = 'CONTOSO\WindowsUser'
            ServerName           = 'sqltest.company.local'
            InstanceName         = 'DSC'

            PsDscRunAsCredential = $SqlAdministratorCredential
        }
    }
}
```

If the following configuration would be compiled it would throw an error because we are trying to use the same resource instance with the same key properties twice. First with the the property `Ensure = 'Present'` then later in the configuration with the property `Ensure = 'Absent'`. This is not allowed since if this would compile it would create the "ping pong" behaviour. Meaning it would first add a login, then remove the login. On the next run it would add the login again, and then again remove it, and so on. _Assuming you have for example the LCM in apply and auto correct mode._

```powershell
Configuration Example
{
    param
    (
        [Parameter(Mandatory = $true)]
        [System.Management.Automation.PSCredential]
        $SqlAdministratorCredential
    )

    Import-DscResource -ModuleName 'SqlServerDsc'

    node localhost
    {
        SqlLogin 'Add_WindowsUser'
        {
            Ensure               = 'Present'
            Name                 = 'CONTOSO\WindowsUser'
            LoginType            = 'WindowsUser'
            ServerName           = 'sqltest.company.local'
            InstanceName         = 'DSC'

            PsDscRunAsCredential = $SqlAdministratorCredential
        }

        # ....

        SqlLogin 'Add_WindowsUser'
        {
            Ensure               = 'Absent'
            Name                 = 'CONTOSO\WindowsUser'
            LoginType            = 'WindowsUser'
            ServerName           = 'sqltest.company.local'
            InstanceName         = 'DSC'

            PsDscRunAsCredential = $SqlAdministratorCredential
        }
    }
}
```
So to your question why SqlRole does not add a login automatically if one is missing. Because then the following configuration would be possible (notice the `Absent` on SqlLogin), and ultimately the node will never get to the desired state. 

```powershell
Configuration Example
{
    param
    (
        [Parameter(Mandatory = $true)]
        [System.Management.Automation.PSCredential]
        $SqlAdministratorCredential
    )

    Import-DscResource -ModuleName 'SqlServerDsc'

    node localhost
    {
        SqlRole 'Add_ServerRole_AdminSqlforBI'
        {
            Ensure               = 'Present'
            ServerRoleName       = 'MySqlRole'
            Members              = 'CONTOSO\WindowsUser'
            ServerName           = 'sqltest.company.local'
            InstanceName         = 'DSC'

            PsDscRunAsCredential = $SqlAdministratorCredential
        }

        SqlLogin 'Add_WindowsUser'
        {
            Ensure               = 'Absent'
            Name                 = 'CONTOSO\WindowsUser'
            LoginType            = 'WindowsUser'
            ServerName           = 'sqltest.company.local'
            InstanceName         = 'DSC'

            PsDscRunAsCredential = $SqlAdministratorCredential
        }
    }
}
```

**Comment by jeremiahmoree-adot** [comment]
Closed this issue as it seems that the system is working as expected.  I also will not be using this 'feature'.  When running DSC to add the login and role setup it trashes the DSC SQL install so badly that I have to throw the whole server away and start over.  Reverting the DSC configuration is not enough to correct the 'state' so it seems I still don't understand how this all works.
