### ISSUE TITLE
SqlSetup: Does not allow null or empty password for MSA

### ISSUE THREAD

**Issue by wasabii** [dsccommunity/SqlServerDsc#378]
"The password supplied to the Desired State Configuration resource MSFT_xSQLServerSetup is not valid. The password cannot be null or empty.",

It should, for managed service accounts.

**Comment by johlju** [comment]
@wasabii Would you be so kind to post the configuration you are using? Without any sensitive information.

**Comment by wasabii** [comment]
I don't think it matters. I solved the problem by creating a PSCredential with a single space as a password. It's sort of hacky, but it works.

**Comment by johlju** [comment]
This was discussed in [Gitter](https://gitter.im/PowerShell/DscResources), thanks @NReilingh! 🙂 

@NReilingh was kind enough to provide the error message from LCM when passing an empty password into the credential object.

Using this compiles a configuration correctly.
```powershell
$SqlProxyUserCredential = New-Object System.Management.Automation.PSCredential(
    $Node.SqlSetup.ProxyUserMSA,
    (New-Object System.Security.SecureString)
)
``` 

But applying the configuration it gives this error.
```
Job {E69E204B-B6C0-11E8-B215-00505697B552} : 
Message Cannot unprotect message. The input contained no encrypted content. Specify the '-IncludeContext' parameter if you wish to output the original content when no encrypted content is detected. 
HResult -2146233087 
StackTrack    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.CMS_DecryptMessage(String thumbprint, String encryptedMessage, IStreamsHandler plugInStreamsHandler, String& outputResult, IntPtr& errorInstanceHandle)
```

And @NReilingh concludes

> So: it’s a MOF file that uses certificate encryption for credentials, but since I use some credentials with empty securestrings, in the MOF these look like Password = “”; instead of Password = “-----BEGIN CMS-----\nblahblahblah

**Comment by johlju** [comment]
To use a (g)MSA with the credential objects (that support (g)MSA), any password need to passed into credential objects, but the username will only be used.

https://github.com/PowerShell/SqlServerDsc/blob/80172377320659488f0b45595264c29da58ae448/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1#L2271-L2277

Since we can not change how LCM or MOF works in this repository, the only other way of solving this is to make separate parameters for (g)MSA, like what was done in https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/441 for the xService resource. 
But for the SqlSetup resource I do not think that is the way to go, since that would mean we have to add many more parameters, with even more logic.

I relabel this as a community discussion since this needs more voices if we should do a (breaking) change.

**Comment by johlju** [comment]
I agree we should add this to the documentation. Labeling it as such.
