### ISSUE TITLE
SqlSetup: Module does not support installed feature BIDS

### ISSUE THREAD

**Issue by Denverrr3** [dsccommunity/SqlServerDsc#69]
https://www.bountysource.com/issues/27794416-trouble-installing-the-feature-rs_shpwfe

Looks like get-TargetResource does not support detection of the following rolls which we need for our SQL Server install.

**Comment by forensicsguy20012004** [comment]
Yeah, I found that out as well, early on but I have yet had the time to get around to re-coding. It would be great if someone with the time could pick this up.

**Comment by wsmelton** [comment]
Just a note on this one, that it seems this is more than just the features listed in this bug. So I tried to use this features list: `SQLENGINE,SSMS,ADV_SSMS,SNAC_SDK,SDK,BC,Conn` and `Test-TargetResource` is returning `false`, BUT the features are still installed. 

I have not dug into the `Get-TargetResource` for xSqlServerSetup module, but quick check and it seems there a few issues:

- The features is a string instead of an array. Not sure what the reasoning behind not having this be an array to begin with was, instead of having to split it.

- Get-TargetResource does not seem to handle anything other than the SSMS options and the components. Anything else it never validates so always returns false, not sure but this may be the only thing needed to fix it (?).

**Comment by pmcevoy** [comment]
Likewise, it doesn't work for the parent feature parameter "TOOLS".

**Comment by johlju** [comment]
Only BIDS left to support. BC and CONN is supported. Changing title to reflect that.

**Comment by johlju** [comment]
Feature BIDS should only exist in SQL Server 2008 R2 for installing **Business Intelligence Development Studio**, and SQL Server 2012 for installing **SQL Server Data Tools (SSDT)**.

**Comment by ptoluganti** [comment]
below code worked for me to check what FEATURES are installed, i have added below code in 
MSFT_xSQLServerSetup -> Get-TargetResource.

i have installed "SQLENGINE,BIDS,CONN,IS,BOL,SSMS,ADV_SSMS,SNAC_SDK" 

if(Test-Path "$env:programfiles\Microsoft SQL Server\$($sqlVersion)0\Setup Bootstrap")
    {
        $file = Get-ChildItem -Path "$env:programfiles\Microsoft SQL Server\$($sqlVersion)0\Setup Bootstrap\Log" -Filter "*.ini" -Recurse | `
            Select-String -pattern "INSTANCENAME=`"$InstanceName`"" | select -Property Path

        if($file -ne $null)
        {
            $features = (Select-String $file.Path -pattern "FEATURES=*" -CaseSensitive).Line.Replace("FEATURES=", "")
        }
    }

**Comment by johlju** [comment]
Updating this issue with a suggestions from @ptoluganti in issue #653. @ptoluganti suggest the following code to detect BIDS.

```
# Check if BIDS in installed
$BIDSRegistryPath = "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\$($sqlVersion)0\BIDS\\*"

$isBIDSInstalled = (Get-ItemProperty -Path $BIDSRegistryPath -ErrorAction SilentlyContinue)
if ($isBIDSInstalled)
{
	$features += 'BIDS,'
}
else
{
	"BIDS Not found"
}
```

After installation of BIDS the following registry keys exist.

HKLM\SOFTWARE\Microsoft\Microsoft SQL Server\110\BIDS
HKLM\SOFTWARE\Microsoft\Microsoft SQL Server\110\BIDS\Setup
HKLM\SOFTWARE\Microsoft\Microsoft SQL Server\110\BIDS\Setup\SQL_BIDS_Full
HKLM\SOFTWARE\Microsoft\Microsoft SQL Server\110\BIDS\Setup\SQL_BIDS_Full\1033

Registry Key:
FeatureList has value SQL_BIDS_Full=3 SQL_WarehouseDevWorkbench_FNS=3

**Comment by johlju** [comment]
Closing this as SQL Server 2008 R2 has reached end-of-life.
