### ISSUE TITLE
SqlScript: The parameter ServiceInstance should be split to ServerName and InstanceName

### ISSUE THREAD

**Issue by johlju** [dsccommunity/SqlServerDsc#925]
**Details of the scenario you tried and the problem that is occurring:**
To align the SqlScript resource with the work being done renaming parameters in issue #308, the parameter ServiceInstance should be split into two parameters `ServerName` and `InstanceName`.

https://github.com/PowerShell/SqlServerDsc/blob/9a1080c4da5d513eb4191388206cf37c16c0a0fd/DSCResources/MSFT_SqlScript/MSFT_SqlScript.schema.mof#L4

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by sql-sith** [comment]
This approach is obviously the better one, but since I need to patch the scripts I use in Amazon Cloud Formation because of this, I wonder: could this be done as a non-breaking change, where there is still an optional ServerInstance parameter? A user could then supply InstanceName only (with ServerName defaulting to localhost?), ServerName and InstanceName, or ServerInstance only. Any other combinations would be prohibited.
